### ISSUE TITLE
Error running binary on M1 chip

### ISSUE THREAD

**Issue by hamzamuric** [natalie-lang/natalie#524] opened 2022-03-06 15:33 UTC
I compiled natalie on Apple M1 chip and when tryed to run it, i got this error message.

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
/Users/hamza/Dev/natalie/lib/natalie/compiler/pass1.rb:4:in `require_relative': cannot load such file -- /Users/hamza/Dev/natalie/build/generated/numbers (LoadError)
	from /Users/hamza/Dev/natalie/lib/natalie/compiler/pass1.rb:4:in `<top (required)>'
	from /Users/hamza/Dev/natalie/lib/natalie/compiler.rb:4:in `require_relative'
	from /Users/hamza/Dev/natalie/lib/natalie/compiler.rb:4:in `<top (required)>'
	from /Users/hamza/Dev/natalie/lib/natalie.rb:1:in `require_relative'
	from /Users/hamza/Dev/natalie/lib/natalie.rb:1:in `<top (required)>'
	from bin/natalie:12:in `require_relative'
	from bin/natalie:12:in `<main>'
```

**Comment by seven1m** [comment] 2022-03-10 13:05
I'm sorry you're having this problem, but none of us can reproduce. Can you post the output you get when you run `rake`?

**Comment by seven1m** [comment] 2022-03-23 12:04
Closing because we cannot reproduce. If you share the output from `rake`, that will help!

**Closed** 2022-03-23 12:03 UTC
