### ISSUE TITLE
Valgrind Errors and Leaks

### ISSUE THREAD

**Issue by Caleb-o** [natalie-lang/natalie#525] opened 2022-03-06 16:12 UTC
Going through the examples, I tried using valgrind. I was informed about the `-d valgrind` flag and that also causes errors and leaks.

Compiling the program first and passing it through to valgrind also causes errors, but ends in a large leak, where the `-d valgrind` results in more errors and less of a leak. A lot seems to be put down to `realloc` in the `grow` function in `vector` and from `new` from `set_str` in the `string` class.

Running `bin/natalie -d valgrind ./examples/hello.rb` will result in quite a large sum of information:
Note: I had to cut a lot out due to limitations.
```
"cpp file path is: /tmp/natalie.cpp20220307-94-mholar"
==94== Memcheck, a memory error detector
==94== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==94== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==94== Command: /tmp/natalie20220307-94-17x6g6y
==94==
==94== Mismatched free() / delete / delete []
==94==    at 0x483DFAF: realloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x119C7D: TM::Vector<Natalie::Value>::grow(unsigned long) (vector.hpp:261)
==94==    by 0x119C22: TM::Vector<Natalie::Value>::grow_at_least(unsigned long) (vector.hpp:277)
==94==    by 0x118C5C: TM::Vector<Natalie::Value>::set_capacity(unsigned long) (vector.hpp:187)
==94==    by 0x129A3F: Natalie::ArrayObject::ArrayObject(std::initializer_list<Natalie::Value>) (array_object.hpp:30)
==94==    by 0x1B4C52: enumerator_class_body63(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2735)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B570D: enumerator_class_body1(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2793)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B6578: init_obj_enumerator(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2914)
==94==    by 0x1163B5: build_top_env (natalie.cpp20220307-94-mholar:43)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==  Address 0x4fb7b90 is 0 bytes inside a block of size 160 alloc'd
==94==    at 0x483C583: operator new[](unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x119BA0: TM::Vector<Natalie::Value>::array_of_size(unsigned long) (vector.hpp:252)
==94==    by 0x118BFA: TM::Vector<Natalie::Value>::Vector() (vector.hpp:19)
==94==    by 0x117C9F: Natalie::ArrayObject::ArrayObject() (array_object.hpp:21)
==94==    by 0x129A20: Natalie::ArrayObject::ArrayObject(std::initializer_list<Natalie::Value>) (array_object.hpp:29)
==94==    by 0x1B4C52: enumerator_class_body63(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2735)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B570D: enumerator_class_body1(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2793)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B6578: init_obj_enumerator(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2914)
==94==    by 0x1163B5: build_top_env (natalie.cpp20220307-94-mholar:43)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==
==94== Mismatched free() / delete / delete []
==94==    at 0x483DFAF: realloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x119C7D: TM::Vector<Natalie::Value>::grow(unsigned long) (vector.hpp:261)
==94==    by 0x119C37: TM::Vector<Natalie::Value>::grow_at_least(unsigned long) (vector.hpp:279)
==94==    by 0x118C5C: TM::Vector<Natalie::Value>::set_capacity(unsigned long) (vector.hpp:187)
==94==    by 0x129A3F: Natalie::ArrayObject::ArrayObject(std::initializer_list<Natalie::Value>) (array_object.hpp:30)
==94==    by 0x1443EB: math_module_body1(Natalie::Env*, Natalie::Value) (math.rb.cpp:2664)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x144EE1: init_obj_math(Natalie::Env*, Natalie::Value) (math.rb.cpp:2733)
==94==    by 0x116456: build_top_env (natalie.cpp20220307-94-mholar:50)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==    by 0x116B54: main (natalie.cpp20220307-94-mholar:117)
==94==  Address 0x50a9c70 is 0 bytes inside a block of size 160 alloc'd
==94==    at 0x483C583: operator new[](unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x119BA0: TM::Vector<Natalie::Value>::array_of_size(unsigned long) (vector.hpp:252)
==94==    by 0x118BFA: TM::Vector<Natalie::Value>::Vector() (vector.hpp:19)
==94==    by 0x117C9F: Natalie::ArrayObject::ArrayObject() (array_object.hpp:21)
==94==    by 0x129A20: Natalie::ArrayObject::ArrayObject(std::initializer_list<Natalie::Value>) (array_object.hpp:29)
==94==    by 0x1443EB: math_module_body1(Natalie::Env*, Natalie::Value) (math.rb.cpp:2664)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x144EE1: init_obj_math(Natalie::Env*, Natalie::Value) (math.rb.cpp:2733)
==94==    by 0x116456: build_top_env (natalie.cpp20220307-94-mholar:50)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==    by 0x116B54: main (natalie.cpp20220307-94-mholar:117)
==94==
hello world
==94== Mismatched free() / delete / delete []
==94==    at 0x483D74F: operator delete[](void*) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x118C32: TM::Vector<Natalie::Value>::~Vector() (vector.hpp:48)
==94==    by 0x118529: Natalie::ArrayObject::~ArrayObject() (array_object.hpp:18)
==94==    by 0x26CA13: Natalie::HeapBlock::return_cell_to_free_list(Natalie::Cell const*) (gc.cpp:200)
==94==    by 0x241C31: Natalie::HeapBlock::~HeapBlock() (heap_block.hpp:42)
==94==    by 0x241F15: Natalie::Allocator::~Allocator() (allocator.hpp:27)
==94==    by 0x241FF6: Natalie::Heap::~Heap() (heap.hpp:35)
==94==    by 0x241916: Natalie::clean_up_and_exit(int) (natalie.cpp:786)
==94==    by 0x116B85: main (natalie.cpp20220307-94-mholar:125)
==94==  Address 0x4fb7c70 is 0 bytes inside a block of size 320 alloc'd
==94==    at 0x483DFAF: realloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x119C7D: TM::Vector<Natalie::Value>::grow(unsigned long) (vector.hpp:261)
==94==    by 0x119C22: TM::Vector<Natalie::Value>::grow_at_least(unsigned long) (vector.hpp:277)
==94==    by 0x118C5C: TM::Vector<Natalie::Value>::set_capacity(unsigned long) (vector.hpp:187)
==94==    by 0x129A3F: Natalie::ArrayObject::ArrayObject(std::initializer_list<Natalie::Value>) (array_object.hpp:30)
==94==    by 0x1B4C52: enumerator_class_body63(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2735)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B570D: enumerator_class_body1(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2793)
==94==    by 0x24522E: Natalie::ModuleObject::eval_body(Natalie::Env*, Natalie::Value (*)(Natalie::Env*, Natalie::Value)) (module_object.cpp:164)
==94==    by 0x1B6578: init_obj_enumerator(Natalie::Env*, Natalie::Value) (enumerator.rb.cpp:2914)
==94==    by 0x1163B5: build_top_env (natalie.cpp20220307-94-mholar:43)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==
==94==
==94== HEAP SUMMARY:
==94==     in use at exit: 5,758 bytes in 416 blocks
==94==   total heap usage: 18,414 allocs, 17,998 frees, 1,267,541 bytes allocated
==94==
==94== 3 bytes in 1 blocks are definitely lost in loss record 1 of 243
==94==    at 0x483C583: operator new[](unsigned long) (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==94==    by 0x1171DB: TM::String::set_str(char const*, unsigned long) (string.hpp:163)
==94==    by 0x16217E: TM::String::operator=(TM::String const&) (string.hpp:97)
==94==    by 0x24B849: TM::Optional<TM::String>::operator=(TM::String&&) (optional.hpp:59)
==94==    by 0x2849CA: Natalie::ModuleObject::set_class_name(Natalie::ManagedString const*) (module_object.hpp:68)
==94==    by 0x2845CC: Natalie::ClassObject::initialize_subclass(Natalie::ClassObject*, Natalie::Env*, Natalie::ManagedString const*, Natalie::ObjectType) (class_object.cpp:41)
==94==    by 0x2844D6: Natalie::ClassObject::subclass(Natalie::Env*, Natalie::ManagedString const*, Natalie::ObjectType) (class_object.cpp:27)
==94==    by 0x11EEED: Natalie::ClassObject::subclass(Natalie::Env*, char const*, Natalie::ObjectType) (class_object.hpp:40)
==94==    by 0x23BDC5: Natalie::build_top_env() (natalie.cpp:141)
==94==    by 0x116308: build_top_env (natalie.cpp20220307-94-mholar:35)
==94==    by 0x1167E4: _main(int, char**) (natalie.cpp20220307-94-mholar:88)
==94==    by 0x116B54: main (natalie.cpp20220307-94-mholar:117)
==94==

[Cut]

==94==
==94== LEAK SUMMARY:
==94==    definitely lost: 5,646 bytes in 414 blocks
==94==    indirectly lost: 0 bytes in 0 blocks
==94==      possibly lost: 0 bytes in 0 blocks
==94==    still reachable: 112 bytes in 2 blocks
==94==         suppressed: 0 bytes in 0 blocks
==94==
==94== For lists of detected and suppressed errors, rerun with: -s
==94== ERROR SUMMARY: 245 errors from 244 contexts (suppressed: 0 from 0)
````

**Comment by seven1m** [comment] 2022-03-23 12:05
@Caleb-o thanks for reporting this, it's definitely on the list to get these fixed. Actually, I'm going to close this as a duplicate of #55, which I've been wanting to work on for awhile. I'll try to focus some effort there over the next few weeks. :heart:

**Closed by seven1m** 2022-03-23 12:05 UTC
